In [ ]:
from datasets import load_dataset
import pandas as pd
import numpy as np
import sys
from pathlib import Path

SEED = 987

DIR_ROOT = Path.cwd().parent
sys.path.insert(0, str(DIR_ROOT))

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
import data

listings = data.load("listings")
off_market = data.load("off_market")
list_aware = data.load("list_aware")

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

In [22]:
print("####### Listings Head ###########")
display(listings.head())
print("####### Off Market Head ###########")
display(off_market.head())
print("####### List Aware Head ###########")
display(list_aware.head())

####### Listings Head ###########

,ml_num,sold_price,list_price,date_listed,date_sold,days_on_market,house_type_name,house_style,bedrooms,washrooms,...,house_area,lot_front,lot_depth,municipality,community,latitude,longitude,external_avm_estimate,external_avm_estimate_date,remarks
0,SYN-0023247,364100.0,371200.0,2020-12-29,2021-01-01,3,Condo Apt,Apartment,1,1,...,622,NaN,NaN,Toronto,Sumacpark,43.602039,-79.261184,366200.0,2021-02-14,Looking For More Space In A Turnkey Condo? Thi...
1,SYN-0156988,599000.0,595800.0,2020-12-26,2021-01-01,6,Condo Apt,Apartment,2,1,...,649,NaN,NaN,Toronto,Hickorymills,43.695388,-79.510865,622800.0,2021-12-26,"Imagine a quiet evening on Sequoia Trail, wher..."
2,SYN-0087706,492900.0,462200.0,2020-12-22,2021-01-01,10,Condo Apt,Apartment,2,1,...,900-1099,NaN,NaN,North York,Hazelmills,43.740512,-79.386216,NaN,2020-12-03,"Discover this inviting 2-bedroom, 1-bath condo..."
3,SYN-0128154,532300.0,524900.0,2020-12-19,2021-01-01,13,Condo Apt,Apartment,1,1,...,876,NaN,NaN,Scarborough,Sumacbank,43.643774,-79.470180,573600.0,2021-02-22,Sumacbank presents this 1-bedroom condo on Mag...
4,SYN-0118596,564100.0,558300.0,2020-12-05,2021-01-01,27,Condo Apt,Apartment,1,1,...,514,NaN,NaN,Toronto,Ashworth,43.696172,-79.274137,513000.0,2021-02-05,"Morning coffee at the kitchen island, then a s..."

####### Off Market Head ###########

,ml_num,date_listed,house_type_name,house_style,bedrooms,washrooms,parking_total,garage,house_area,lot_front,lot_depth,municipality,community,latitude,longitude,remarks
0,SYN-0011818,2026-05-04,Condo Apt,Apartment,1,1,0,0.0,300-499,NaN,NaN,North York,Hawthornbourne,43.594328,-79.416373,"Located on Elm Crescent, this one-bedroom apar..."
1,SYN-0117584,2026-08-15,Semi-Detached,2-Storey,3,2,2,1.0,1555,21.23,140.10,Scarborough,Spruceview,43.590486,-79.315004,Magnolia Ave in Spruceview – a solid semi with...
2,SYN-0065643,2026-05-05,Condo Apt,Apartment,1,1,1,0.0,685,NaN,NaN,Toronto,Sprucehaven,43.604231,-79.368203,Looking for more space in a condo? This 685 sq...
3,SYN-0031502,2026-09-04,Condo Apt,Apartment,2,1,0,0.0,500-699,NaN,NaN,Toronto,Cypressdale,43.720574,-79.388083,If you're a small family looking for a smart s...
4,SYN-0003276,2026-06-05,Detached,2-Storey,5,5,2,2.0,2844,65.17,129.14,Scarborough,Rowangardens,43.688588,-79.437290,Experience life on Spruce Crescent in Rowangar...

####### List Aware Head ###########

,ml_num,list_price,date_listed,house_type_name,house_style,bedrooms,washrooms,parking_total,garage,house_area,lot_front,lot_depth,municipality,community,latitude,longitude,remarks
0,SYN-0120320,624700.0,2026-08-27,Condo Apt,Apartment,1,1,1,0.0,657,NaN,NaN,Etobicoke,Cedarglen,43.628228,-79.213146,Cedarglen offers this move-in-ready 1-bedroom ...
1,SYN-0041629,1370000.0,2026-03-28,Detached,2-Storey,4,2,3,0.0,1600-1799,34.00,97.26,Scarborough,Maplegrove,43.686642,-79.475803,"If your family needs room to grow, this 4-bedr..."
2,SYN-0070828,3101400.0,2026-07-22,Detached,2 1/2 Storey,3,3,2,0.0,2700,63.36,110.88,Toronto,Poplarcrest,43.648734,-79.394781,"Professionals, This Stunning 2 1/2 Storey Home..."
3,SYN-0102921,513500.0,2026-05-15,Condo Apt,Apartment,1,1,1,0.0,673,NaN,NaN,Toronto,Cypressdale,43.743930,-79.393589,Move-In Ready 1-Bedroom Plus Den In Cypressdal...
4,SYN-0096074,544400.0,2026-09-14,Condo Apt,Apartment,1,1,1,0.0,520,NaN,NaN,Toronto,Cypresspark,43.572223,-79.364242,The den in this 1-bedroom condo apartment on A...

In [23]:
print("####### Listings Info ###########")
display(listings.info())
print("####### Off Market Info ###########")
display(off_market.info())
print("####### List Aware Info ###########")
display(list_aware.info())

####### Listings Info ###########
<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   ml_num                      150000 non-null  str
 1   sold_price                  150000 non-null  float64
 2   list_price                  150000 non-null  float64
 3   date_listed                 150000 non-null  datetime64[us]
 4   date_sold                   150000 non-null  datetime64[us]
 5   days_on_market              150000 non-null  int64
 6   house_type_name             150000 non-null  str
 7   house_style                 150000 non-null  str
 8   bedrooms                    150000 non-null  int64
 9   washrooms                   150000 non-null  int64
 10  parking_total               150000 non-null  int64
 11  garage                      150000 non-null  float64
 12  house_area                  150000 non-null  str
 13  lot_front                   62737 non-null   float64
 14  lot_depth                   62737 non-null   float64
 15  municipality                150000 non-null  str
 16  community                   150000 non-null  str
 17  latitude                    150000 non-null  float64
 18  longitude                   150000 non-null  float64
 19  external_avm_estimate       148694 non-null  float64
 20  external_avm_estimate_date  150000 non-null  datetime64[us]
 21  remarks                     150000 non-null  str
dtypes: datetime64[us](3), float64(8), int64(4), str(7)
memory usage: 87.6 MB

None

####### Off Market Info ###########
<class 'pandas.DataFrame'>
RangeIndex: 3974 entries, 0 to 3973
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ml_num           3974 non-null   str
 1   date_listed      3974 non-null   datetime64[us]
 2   house_type_name  3974 non-null   str
 3   house_style      3974 non-null   str
 4   bedrooms         3974 non-null   int64
 5   washrooms        3974 non-null   int64
 6   parking_total    3974 non-null   int64
 7   garage           3974 non-null   float64
 8   house_area       3974 non-null   str
 9   lot_front        1825 non-null   float64
 10  lot_depth        1825 non-null   float64
 11  municipality     3974 non-null   str
 12  community        3974 non-null   str
 13  latitude         3974 non-null   float64
 14  longitude        3974 non-null   float64
 15  remarks          3974 non-null   str
dtypes: datetime64[us](1), float64(5), int64(3), str(7)
memory usage: 2.1 MB

None

####### List Aware Info ###########
<class 'pandas.DataFrame'>
RangeIndex: 4064 entries, 0 to 4063
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ml_num           4064 non-null   str
 1   list_price       4064 non-null   float64
 2   date_listed      4064 non-null   datetime64[us]
 3   house_type_name  4064 non-null   str
 4   house_style      4064 non-null   str
 5   bedrooms         4064 non-null   int64
 6   washrooms        4064 non-null   int64
 7   parking_total    4064 non-null   int64
 8   garage           4064 non-null   float64
 9   house_area       4064 non-null   str
 10  lot_front        1909 non-null   float64
 11  lot_depth        1909 non-null   float64
 12  municipality     4064 non-null   str
 13  community        4064 non-null   str
 14  latitude         4064 non-null   float64
 15  longitude        4064 non-null   float64
 16  remarks          4064 non-null   str
dtypes: datetime64[us](1), float64(6), int64(3), str(7)
memory usage: 2.2 MB

None

In [24]:
print("####### Listings Describe ###########")
display(listings.describe())
print("####### Off Market Describe ###########")
display(off_market.describe())
print("####### List Aware Describe ###########")
display(list_aware.describe())

####### Listings Describe ###########

,sold_price,list_price,date_listed,date_sold,days_on_market,bedrooms,washrooms,parking_total,garage,lot_front,lot_depth,latitude,longitude,external_avm_estimate,external_avm_estimate_date
count,1.500000e+05,1.500000e+05,150000,150000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,62737.000000,62737.000000,150000.000000,150000.000000,1.486940e+05,150000
mean,1.073917e+06,1.074505e+06,2023-04-16 14:02:04.992000,2023-05-08 20:15:59.040000,22.259653,2.341673,2.158313,1.853387,0.411860,36.329378,119.334418,43.643452,-79.378654,1.082145e+06,2023-09-22 02:26:47.040000
min,1.726000e+05,1.618000e+05,2020-02-19 00:00:00,2021-01-01 00:00:00,0.000000,0.000000,1.000000,0.000000,0.000000,10.000000,40.000000,43.490027,-79.597572,1.985000e+05,2020-12-03 00:00:00
25%,6.237000e+05,6.317000e+05,2021-10-25 00:00:00,2021-11-08 00:00:00,6.000000,1.000000,1.000000,1.000000,0.000000,22.930000,98.870000,43.600888,-79.445734,6.189000e+05,2022-04-05 00:00:00
50%,8.566500e+05,8.597000e+05,2023-03-11 00:00:00,2023-03-30 00:00:00,12.000000,2.000000,2.000000,1.000000,0.000000,32.530000,116.650000,43.642058,-79.391685,8.555000e+05,2023-07-18 00:00:00
75%,1.239800e+06,1.233900e+06,2024-08-24 00:00:00,2024-09-28 00:00:00,26.000000,3.000000,3.000000,3.000000,1.000000,46.060000,136.920000,43.679629,-79.313684,1.251200e+06,2025-02-17 00:00:00
max,3.000000e+07,2.807800e+07,2026-05-29 00:00:00,2026-05-31 00:00:00,320.000000,6.000000,6.000000,6.000000,6.000000,150.000000,300.000000,43.843841,-79.070793,2.807060e+07,2027-06-30 00:00:00
std,8.125300e+05,8.104716e+05,NaN,NaN,31.628163,1.106252,1.109122,1.647204,0.713168,17.609140,30.694320,0.054368,0.100594,8.404389e+05,NaN

####### Off Market Describe ###########

,date_listed,bedrooms,washrooms,parking_total,garage,lot_front,lot_depth,latitude,longitude
count,3974,3974.000000,3974.000000,3974.000000,3974.000000,1825.000000,1825.000000,3974.000000,3974.000000
mean,2026-06-21 21:22:22.526421,2.411424,2.218420,1.939859,0.448918,36.379063,119.583540,43.641871,-79.378137
min,2025-08-01 00:00:00,0.000000,1.000000,0.000000,0.000000,10.000000,40.000000,43.490267,-79.585263
25%,2026-05-25 00:00:00,2.000000,1.000000,1.000000,0.000000,23.070000,98.870000,43.600048,-79.445808
50%,2026-06-24 00:00:00,2.000000,2.000000,1.000000,0.000000,32.590000,117.370000,43.640693,-79.390148
75%,2026-08-01 00:00:00,3.000000,3.000000,3.000000,1.000000,45.520000,137.600000,43.677483,-79.310224
max,2026-09-28 00:00:00,6.000000,6.000000,6.000000,4.000000,129.110000,295.210000,43.826056,-79.084804
std,NaN,1.121863,1.141666,1.688461,0.724796,17.712243,29.951076,0.053972,0.100982

####### List Aware Describe ###########

,list_price,date_listed,bedrooms,washrooms,parking_total,garage,lot_front,lot_depth,latitude,longitude
count,4.064000e+03,4064,4064.000000,4064.000000,4064.000000,4064.000000,1909.000000,1909.000000,4064.000000,4064.000000
mean,1.010361e+06,2026-06-22 16:40:16.535433,2.416831,2.184301,1.951280,0.468258,36.380927,118.266307,43.642554,-79.378969
min,2.162000e+05,2025-07-24 00:00:00,0.000000,1.000000,0.000000,0.000000,10.000000,40.000000,43.490267,-79.585263
25%,5.786000e+05,2026-05-27 00:00:00,2.000000,1.000000,1.000000,0.000000,22.700000,97.640000,43.599992,-79.447012
50%,8.162500e+05,2026-06-25 00:00:00,2.000000,2.000000,1.000000,0.000000,31.880000,116.150000,43.640271,-79.391386
75%,1.188150e+06,2026-08-01 00:00:00,3.000000,3.000000,3.000000,1.000000,45.990000,135.310000,43.679285,-79.313777
max,1.912610e+07,2026-09-28 00:00:00,6.000000,6.000000,6.000000,6.000000,127.050000,282.880000,43.836356,-79.086243
std,7.608424e+05,NaN,1.113085,1.114529,1.699296,0.744808,18.138679,29.872057,0.055412,0.101527

In [25]:
print("####### Listings NA ###########")
display(listings.isnull().sum())
print("####### Off Market NA ###########")
display(off_market.isnull().sum())
print("####### List Aware NA ###########")
display(list_aware.isnull().sum())

####### Listings NA ###########

ml_num                            0
sold_price                        0
list_price                        0
date_listed                       0
date_sold                         0
days_on_market                    0
house_type_name                   0
house_style                       0
bedrooms                          0
washrooms                         0
parking_total                     0
garage                            0
house_area                        0
lot_front                     87263
lot_depth                     87263
municipality                      0
community                         0
latitude                          0
longitude                         0
external_avm_estimate          1306
external_avm_estimate_date        0
remarks                           0
dtype: int64

####### Off Market NA ###########

ml_num                0
date_listed           0
house_type_name       0
house_style           0
bedrooms              0
washrooms             0
parking_total         0
garage                0
house_area            0
lot_front          2149
lot_depth          2149
municipality          0
community             0
latitude              0
longitude             0
remarks               0
dtype: int64

####### List Aware NA ###########

ml_num                0
list_price            0
date_listed           0
house_type_name       0
house_style           0
bedrooms              0
washrooms             0
parking_total         0
garage                0
house_area            0
lot_front          2155
lot_depth          2155
municipality          0
community             0
latitude              0
longitude             0
remarks               0
dtype: int64

In [29]:
listings_features = listings.columns
off_market_features = off_market.columns
list_aware_features = list_aware.columns

list_features_diff_off_market = set(listings_features) - set(off_market_features)
list_features_diff_list_aware = set(listings_features) - set(list_aware_features)

print("####### Listings Features ###########")
print(listings_features)
print("\n")

print("####### Off Market Features ###########")
print(off_market_features)
print("\n")

print("####### List Aware Features ###########")
print(list_aware_features)
print("\n")

print("####### Features in Listings but not in Off Market ###########")
print(list_features_diff_off_market)
print("\n")

print("####### Features in Listings but not in List Aware ###########")
print(list_features_diff_list_aware)
print("\n")

print("####### Features in All Datasets ###########")
print(set(listings_features) & set(off_market_features) & set(list_aware_features))
print("\n")

print("####### Features in Off Market but not in List Aware ###########")
print(set(off_market_features) - set(list_aware_features))
print("\n")

print("####### Features in List Aware but not in Off Market ###########")
print(set(list_aware_features) - set(off_market_features))
print("\n")

####### Listings Features ###########
Index(['ml_num', 'sold_price', 'list_price', 'date_listed', 'date_sold',
       'days_on_market', 'house_type_name', 'house_style', 'bedrooms',
       'washrooms', 'parking_total', 'garage', 'house_area', 'lot_front',
       'lot_depth', 'municipality', 'community', 'latitude', 'longitude',
       'external_avm_estimate', 'external_avm_estimate_date', 'remarks'],
      dtype='str')


####### Off Market Features ###########
Index(['ml_num', 'date_listed', 'house_type_name', 'house_style', 'bedrooms',
       'washrooms', 'parking_total', 'garage', 'house_area', 'lot_front',
       'lot_depth', 'municipality', 'community', 'latitude', 'longitude',
       'remarks'],
      dtype='str')


####### List Aware Features ###########
Index(['ml_num', 'list_price', 'date_listed', 'house_type_name', 'house_style',
       'bedrooms', 'washrooms', 'parking_total', 'garage', 'house_area',
       'lot_front', 'lot_depth', 'municipality', 'community', 'latitude',
       'longitude', 'remarks'],
      dtype='str')


####### Features in Listings but not in Off Market ###########
{'sold_price', 'external_avm_estimate', 'list_price', 'days_on_market', 'external_avm_estimate_date', 'date_sold'}


####### Features in Listings but not in List Aware ###########
{'sold_price', 'external_avm_estimate', 'days_on_market', 'external_avm_estimate_date', 'date_sold'}


####### Features in All Datasets ###########
{'remarks', 'bedrooms', 'date_listed', 'washrooms', 'parking_total', 'lot_front', 'house_style', 'lot_depth', 'longitude', 'latitude', 'community', 'garage', 'house_type_name', 'house_area', 'municipality', 'ml_num'}


####### Features in Off Market but not in List Aware ###########
set()


####### Features in List Aware but not in Off Market ###########
{'list_price'}

In [30]:
print("####### Unique Features in Listings ###########")
print(listings.nunique())

####### Unique Features in Listings ###########
ml_num                        150000
sold_price                     25452
list_price                     25274
date_listed                     2105
date_sold                       1977
days_on_market                   317
house_type_name                    6
house_style                       16
bedrooms                           7
washrooms                          6
parking_total                      7
garage                             7
house_area                      4884
lot_front                       7745
lot_depth                      13617
municipality                       5
community                        145
latitude                       62844
longitude                      62844
external_avm_estimate          25810
external_avm_estimate_date      2399
remarks                       149999
dtype: int64

In [ ]:
numerical_features = ['sold_price', 'list_price', 'days_on_market', 'bedrooms', 'washrooms',
                      'parking_total', 'garage', 'lot_front', 'lot_depth', 'latitude',
                      'longitude', 'external_avm_estimate']
categorical_features = ['ml_num', 'house_type_name', 'house_style', 'house_area',
                        'municipality', 'community']

print("####### Numerical Features in Listings ###########")
print(numerical_features)
print("\n")

print("####### Categorical Features in Listings ###########")
print(categorical_features)
print("\n")

####### Numerical Features in Listings ###########
Index(['sold_price', 'list_price', 'days_on_market', 'bedrooms', 'washrooms',
       'parking_total', 'garage', 'lot_front', 'lot_depth', 'latitude',
       'longitude', 'external_avm_estimate'],
      dtype='str')


####### Categorical Features in Listings ###########
Index(['ml_num', 'house_type_name', 'house_style', 'house_area',
       'municipality', 'community', 'remarks'],
      dtype='str')

/tmp/ipykernel_1908092/2153198866.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = listings.select_dtypes(include=[object]).columns

## What Do the Features and the Data Mean:
### Different Datasets:
- listings: this includes all the available features from `off market` and `list aware` + some extra.
- Off Market Price: a dataset to predict sale price of houses when not given the list price
- List Aware Price: given the list price, predict the sale price of the house

For both the `off market` dataset and the `list aware` dataset, you are predicting the sales price as the target.

### Features
Features in All Datasets: ml_num, remarks, bedrooms, date_listed, washrooms, parking_total, lot_front, house_style, lot_depth, longitude, latitude, community, garage, house_type_name, house_area, municipality
Features that Don't Appear in Test Splits: external_avm_estimate, days_on_market, external_avm_estimate_date, date_sold

Meaning of Features:
- ml_num: the unique identifier for the observation
- remarks: notes about the house in the listing (written by an AI...)
- bedrooms: number of bedrooms (0-6)
- date_listed: Just the date listed...
- washrooms: Number of washrooms (1 - 6)
- parking_total: number of parking spots (0-6)
- lot_front: width of the property (ft)
- house_style: what style the house is (16 unique)
- lot_depth: how deep the property is from front to back (ft)
- longitude: east west coordinates
- latitude: north south coordinates
- community: what community the house is in (145 unique)
- garage: number of garages (0-6)
- house_type_name: what kind of house it is (6 unique)
- house_area: are of the house (sq ft, sometimes a range)
- municipality: what municipality house is in (5 unique)

Meaning of Listings Only Features:
- external_avm_estimate: the price estimated by a 3rd party
- days_on_market: how long the house has been on the market
- external_avm_estimate_date: the date of the 3rd party estimate, only informative if it is before the selling date
- date_sold: when the house was sold

#### Additional Considerations for Features
- for the categorical features (house_type_name, municipality, house_style, community) consider whether or not these features may be ordinal, ie. is one house style objectively better than another in some way.

## Visualizations Yippee!

In [ ]:
# Distributions for Listings